### ISSUE TITLE
Support setting cpython version via runtime.txt file

### ISSUE THREAD

**Issue by kvedurmu** [paketo-community/cpython#207]
Should we consider allowing users to set a python version via a runtime.txt file? This is a feature supported in Heroku and last-gen CF buildpacks (I ran into a bunch of apps with this file from a github search) so perhaps it could improve the migration path to the paketo buildpack. I'd be happy closing this out though if folks feel the existing environment variable is sufficient.

**Comment by kvedurmu** [comment]
CC/ @arjun024 @ryanmoran

**Comment by ryanmoran** [comment]
I can't find any strong evidence that this is used outside of the Heroku or Cloud Foundry buildpacks. I'd prefer not to bring along these legacy concepts if we have existing supports for managing the version.

**Comment by kvedurmu** [comment]
That sounds good to me. Closing this out.
